"""User password string bump to 255

Revision ID: 41921485374f
Revises: a1ea3185d1e4
Create Date: 2025-02-04 11:24:23.850545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41921485374f'
down_revision = 'a1ea3185d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
